
Tracker:AddLocations("locations/yoshis_island/yoshis_island_1.json")
Tracker:AddLocations("locations/yoshis_island/yoshis_island_2.json")
Tracker:AddLocations("locations/yoshis_island/yoshis_island_3.json")
Tracker:AddLocations("locations/yoshis_island/yoshis_island_4.json")
Tracker:AddLocations("locations/yoshis_island/yoshis_island_castle.json")
Tracker:AddLocations("locations/yoshis_island/yellow_switch_palace.json")

Tracker:AddLocations("locations/donut_plains/donut_plains_1.json")
Tracker:AddLocations("locations/donut_plains/donut_secret_1.json")
Tracker:AddLocations("locations/donut_plains/donut_plains_2.json")
Tracker:AddLocations("locations/donut_plains/donut_ghost_house.json")
Tracker:AddLocations("locations/donut_plains/donut_secret_house.json")
Tracker:AddLocations("locations/donut_plains/donut_plains_3.json")
Tracker:AddLocations("locations/donut_plains/donut_plains_4.json")
Tracker:AddLocations("locations/donut_plains/donut_secret_2.json")
Tracker:AddLocations("locations/donut_plains/donut_plains_castle.json")
Tracker:AddLocations("locations/donut_plains/green_switch_palace.json")

Tracker:AddLocations("locations/vanilla_dome/vanilla_dome_1.json")
Tracker:AddLocations("locations/vanilla_dome/vanilla_secret_1.json")
Tracker:AddLocations("locations/vanilla_dome/vanilla_dome_2.json")
Tracker:AddLocations("locations/vanilla_dome/vanilla_ghost_house.json")
Tracker:AddLocations("locations/vanilla_dome/vanilla_dome_3.json")
Tracker:AddLocations("locations/vanilla_dome/vanilla_dome_4.json")
Tracker:AddLocations("locations/vanilla_dome/vanilla_secret_2.json")
Tracker:AddLocations("locations/vanilla_dome/vanilla_secret_3.json")
Tracker:AddLocations("locations/vanilla_dome/vanilla_fortress.json")
Tracker:AddLocations("locations/vanilla_dome/vanilla_dome_castle.json")
Tracker:AddLocations("locations/vanilla_dome/red_switch_palace.json")

Tracker:AddLocations("locations/twin_bridges/butter_bridge_1.json")
Tracker:AddLocations("locations/twin_bridges/butter_bridge_2.json")
Tracker:AddLocations("locations/twin_bridges/cheese_bridge.json")
Tracker:AddLocations("locations/twin_bridges/cookie_mountain.json")
Tracker:AddLocations("locations/twin_bridges/soda_lake.json")
Tracker:AddLocations("locations/twin_bridges/twin_bridges_castle.json")

Tracker:AddLocations("locations/forest_of_illusion/forest_of_illusion_1.json")
Tracker:AddLocations("locations/forest_of_illusion/forest_of_illusion_2.json")
Tracker:AddLocations("locations/forest_of_illusion/forest_of_illusion_3.json")
Tracker:AddLocations("locations/forest_of_illusion/forest_of_illusion_4.json")
Tracker:AddLocations("locations/forest_of_illusion/forest_ghost_house.json")
Tracker:AddLocations("locations/forest_of_illusion/forest_secret.json")
Tracker:AddLocations("locations/forest_of_illusion/forest_fortress.json")
Tracker:AddLocations("locations/forest_of_illusion/forest_castle.json")
Tracker:AddLocations("locations/forest_of_illusion/blue_switch_palace.json")

Tracker:AddLocations("locations/chocolate_island/chocolate_island_1.json")
Tracker:AddLocations("locations/chocolate_island/chocolate_island_2.json")
Tracker:AddLocations("locations/chocolate_island/chocolate_island_3.json")
Tracker:AddLocations("locations/chocolate_island/chocolate_island_4.json")
Tracker:AddLocations("locations/chocolate_island/chocolate_island_5.json")
Tracker:AddLocations("locations/chocolate_island/chocolate_ghost_house.json")
Tracker:AddLocations("locations/chocolate_island/chocolate_secret.json")
Tracker:AddLocations("locations/chocolate_island/chocolate_fortress.json")
Tracker:AddLocations("locations/chocolate_island/chocolate_castle.json")
Tracker:AddLocations("locations/chocolate_island/sunken_ghost_ship.json")

Tracker:AddLocations("locations/valley_of_bowser/valley_of_bowser_1.json")
Tracker:AddLocations("locations/valley_of_bowser/valley_of_bowser_2.json")
Tracker:AddLocations("locations/valley_of_bowser/valley_of_bowser_3.json")
Tracker:AddLocations("locations/valley_of_bowser/valley_of_bowser_4.json")
Tracker:AddLocations("locations/valley_of_bowser/valley_ghost_house.json")
Tracker:AddLocations("locations/valley_of_bowser/valley_fortress.json")
Tracker:AddLocations("locations/valley_of_bowser/valley_castle.json")
Tracker:AddLocations("locations/valley_of_bowser/front_door.json")
Tracker:AddLocations("locations/valley_of_bowser/back_door.json")

Tracker:AddLocations("locations/star_world/star_world_1.json")
Tracker:AddLocations("locations/star_world/star_world_2.json")
Tracker:AddLocations("locations/star_world/star_world_3.json")
Tracker:AddLocations("locations/star_world/star_world_4.json")
Tracker:AddLocations("locations/star_world/star_world_5.json")

Tracker:AddLocations("locations/special_zone/gnarly.json")
Tracker:AddLocations("locations/special_zone/tubular.json")
Tracker:AddLocations("locations/special_zone/way_cool.json")
Tracker:AddLocations("locations/special_zone/awesome.json")
Tracker:AddLocations("locations/special_zone/groovy.json")
Tracker:AddLocations("locations/special_zone/mondo.json")
Tracker:AddLocations("locations/special_zone/outrageous.json")
Tracker:AddLocations("locations/special_zone/funky.json")
